version: '2'
services:
  elasticsearch:
    build: elasticsearch/
    environment:
      ES_JAVA_OPTS: "-Xms1g -Xmx1g"
    volumes:
      - /mnt/data/elasticsearch/sis2:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    networks:
      - dashboard-sis
  logstash:
    build: logstash/
    command: -f /etc/logstash/conf.d/
    volumes:
      - ./logstash/config:/etc/logstash/conf.d
    ports:
      - "5044:5044"
    networks:
      - dashboard-sis
    depends_on:
      - elasticsearch
  kibana:
    build: kibana/
    volumes:
      - ./kibana/config/:/etc/kibana/
    ports:
      - "5601:5601"
    networks:
      - dashboard-sis
    depends_on:
      - elasticsearch
networks:
  dashboard-sis:
    driver: bridge
