version: '2'
services:
  elasticsearch:
    build: elasticsearch/
    environment:
      ES_JAVA_OPTS: "-Xms1g -Xmx1g"
    volumes:
      - C:\Users\rodrigo.vieira\Documents\elastick-stack\elasticsearch\indices:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    networks:
      - elastic-stack
  logstash:
    build: logstash/
    command: -f /etc/logstash/conf.d/
    volumes:
      - ./logstash/config:/etc/logstash/conf.d
    ports:
      - "5044:5044"
    networks:
      - elastic-stack
    depends_on:
      - elasticsearch
  kibana:
    build: kibana/
    volumes:
      - ./kibana/config/:/etc/kibana/
    ports:
      - "5601:5601"
    networks:
      - elastic-stack
    depends_on:
      - elasticsearch
networks:
  elastic-stack:
    driver: bridge
